{"id":"4z390naxyx1anq66ltmg7u0","title":"Python Custom Exceptions","desc":"","updated":1641270246992,"created":1641168992623,"stub":false,"isDir":false,"custom":{"stub":false,"isDir":false},"fname":"r.(.python-custom-exceptions","type":"note","vault":{"fsPath":"DevLog"},"contentHash":"6d2849d4bb679bc66767996f9fef6e36","links":[{"from":{"fname":"log.daily.2021.09.29","vaultName":"DevLog"},"type":"backlink","position":{"start":{"line":6,"column":3,"offset":83},"end":{"line":6,"column":35,"offset":115},"indent":[]},"value":"r.(.python-custom-exceptions","alias":"r.(.python-custom-exceptions"}],"anchors":{},"children":[],"parent":"l0u7opnawgkmgqvmbji9wx1","data":{}}
